In [14]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets



In [4]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [6]:
x.shape

(150, 4)

In [8]:
y.shape

(150,)

In [11]:
shuffle_indexes = np.random.permutation(len(x))
shuffle_indexes

array([ 54, 147, 134, 104,  51,  16,  41, 105,  57,  31, 145,  29,  37,
        48,  92, 144,  86,  77,  98, 129,  84, 103,  10, 143,  94, 116,
        53,  23,  32,  80, 139,  44, 132,   7, 109, 133,  13,  55,   6,
        11, 117, 149,   2, 124,  15,  60, 118,  33,  99,  20,  39,  24,
        62,  91,  17,  65,  25,  58,  27, 102,  68,  42, 128, 115, 126,
        73,  40,   8,  64,  22,  21, 114, 136, 142,  76,  35, 130,  72,
       138,  90,  67,   9, 100,  75,  50,  85,  38,  59, 141,  30,  69,
       110,  61,   4,   5, 146, 119, 131, 127,  14,  79,  89,   0,  36,
        82,  52,  19,   3, 113,  47,   1, 107, 120, 135,  88,  96,  95,
        83,  56,  71,  93, 121, 108, 125,  74,  12,  97,  63, 111, 123,
       122,  70, 101, 112, 106, 148,  87,  78,  34,  18,  66,  49,  43,
        28,  45, 137,  46, 140,  81,  26])

In [13]:
test_ratio = 0.2
test_size = int(len(x) * test_ratio)
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [16]:
x_train = x[train_indexes]
y_train = y[train_indexes]
x_test = x[test_indexes]
y_test = y[test_indexes]


In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)
predict_y = knn.predict(x_test)

In [20]:
predict_y

array([1, 2, 2, 2, 1, 0, 0, 2, 1, 0, 2, 0, 0, 0, 1, 2, 1, 1, 1, 2, 1, 2,
       0, 2, 1, 2, 1, 0, 0, 1])

In [22]:
y_test

array([1, 2, 2, 2, 1, 0, 0, 2, 1, 0, 2, 0, 0, 0, 1, 2, 1, 1, 1, 2, 1, 2,
       0, 2, 1, 2, 1, 0, 0, 1])

In [24]:
sum(predict_y == y_test)

np.int64(30)

In [26]:
from sklearn.model_selection import train_test_split
x_train1, x_test1, y_train1, y_test1 = train_test_split(x, y, test_size=0.2)